image: node:14

before_script:
  - npm ci

# stages:
#   - build
#   - deploy

# include:
#   template: Jobs/Code-Quality.gitlab-ci.yml

lint_test:
  stage: test
  only:
    - amo_cicd
  script:
    - npm run test

deploy_amo:
  stage: deploy
  only:
    - amo_cicd
  allow_failure: true
  script:
    - npm run deploy-amo

deploy_chrome:
  stage: deploy
  only:
    - amo_cicd
  script:
    - npm run deploy-chrome
