include:
  template: Jobs/Code-Quality.gitlab-ci.yml

code_quality:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: never
    - if: '$CODE_QUALITY_DISABLED'
      when: never

image: node:14

before_script:
  - npm ci

lint_test:
  stage: test
  script:
    - npm run test

deploy_amo:
  stage: deploy
  only:
    - main
  allow_failure: true
  script:
    - npm run deploy-amo

deploy_chrome:
  stage: deploy
  only:
    - main
  script:
    - npm run deploy-chrome
