image: node:14

before_script:
  - npm ci

include:
  template: Jobs/Code-Quality.gitlab-ci.yml

code_quality:
  except:
    - main
  rules:
    - if: '$CODE_QUALITY_DISABLED'
      when: never
#     - if: '$CI_PIPELINE_SOURCE == "merge_request_event"' # Run code quality job in merge request pipelines
#     - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'      # Run code quality job in pipelines on the master branch (but not in other branch pipelines)
#     - if: '$CI_COMMIT_TAG'                               # Run code quality job in pipelines for tags

lint_test:
  stage: test
  script:
    - npm run test

deploy_amo:
  stage: deploy
  only:
    - main
  allow_failure: true
  script:
    - npm run deploy-amo

deploy_chrome:
  stage: deploy
  only:
    - main
  script:
    - npm run deploy-chrome
